// Source: pr_agent/settings/generated_code_ignore.toml, table [generated_code] at PR-Agent commit 8e5a9295973b24af4b70cafd0b660a230811ef9e
// (8e5a929). This is MIT-licensed material adapted from PR-Agent; see NOTICE.
// Generated by a one-off script run outside this repository; do not edit by hand.
//
// Entry counts: frameworks=9 globs=22

package data

// GeneratedCode maps a framework name to its generated-file glob patterns.
var GeneratedCode = map[string][]string{
	"go_gen": {
		"**/*_gen.go",
		"**/*generated.go",
	},
	"graphql": {
		"**/*.graphql.ts",
		"**/*.generated.ts",
		"**/*.graphql.js",
	},
	"grpc_csharp": {
		"**/*Grpc.cs",
	},
	"grpc_java": {
		"**/*Grpc.java",
	},
	"grpc_python": {
		"**/*_grpc.py",
	},
	"grpc_typescript": {
		"**/*_grpc.ts",
		"**/*_grpc.js",
	},
	"openapi": {
		"**/__generated__/**",
		"**/openapi_client/**",
		"**/openapi_server/**",
	},
	"protobuf": {
		"**/*.pb.go",
		"**/*.pb.cc",
		"**/*_pb2.py",
		"**/*.pb.swift",
		"**/*.pb.rb",
		"**/*.pb.php",
		"**/*.pb.h",
	},
	"swagger": {
		"**/swagger.json",
		"**/swagger.yaml",
	},
}
